apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: myweb
  namespace: test-compose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: tomcat
          ports:
          - containerPort: 8080
